### ISSUE TITLE
Comparisons to RWeka etc.

### ISSUE THREAD

**Issue by soodoku** [ropensci/tokenizers#10]
Dear Lincoln,

It would be great to post some test results against RWeka implementation. On my computer, I got the following numbers: 

> system.time( replicate(10000, tokenize_words(james)[[1]] ) )
>    user  system elapsed 
>    1.08    0.27    1.34 
> system.time( replicate(10000, NGramTokenizer(tokenize_words(james)[[1]], RWeka:::Weka_control(min = 1, max = 1)) ) )
>    user  system elapsed 
>   10.90    0.25   10.71

Warmly,

**Comment by lmullen** [comment]
Thanks for the suggestion. I may add something like this to the wiki, but in general I don't want to be unnecessarily critical of other people's work, and I'd prefer to emphasize the consistency of the interface.

**Comment by soodoku** [comment]
But Lincoln, I think this is useful information. And would help people thinking about what package to use when tokenizing.
