### ISSUE TITLE
Bug with tokenize_ngrams when number of words in document is between n_min and n

### ISSUE THREAD

**Issue by lmullen** [ropensci/tokenizers#14]
With `tokenize_ngrams()` (and thus the C++ functions they call) there is a bug if the number of words in the document is between the parameter `n_min` and `n`, and `n` is greater than the number of words in the text plus 1.

Suppose we have a three word text. If we ask for 4-grams, we sensibly get back an empty character vector.

```
tokenizers::tokenize_ngrams("one two three", n = 5, n_min = 5)
#> [[1]]
#> character(0)
```

But if we ask for the range of n-grams between 2-grams and 5-grams, we get an error.

```
tokenizers::tokenize_ngrams("one two three", n = 5, n_min = 2)
#> Error in generate_ngrams_batch(words, ngram_min = n_min, ngram_max = n,  : 
#>   attempt to set index 2/2 in SET_STRING_ELT
```

But note that this works fine if we ask for the n-grams between 2-grams and 4-grams.

```
tokenizers::tokenize_ngrams("one two three", n = 4, n_min = 2)
#> [[1]]
#> [1] "one two"       "one two three" "two three"    
```

@dselivanov Is this something that you would be willing to take a look at?

**Comment by dselivanov** [comment]
I'm on vacation till 10th of May, will take a look after return.
3 мая 2016 г. 7:45 AM пользователь "Lincoln Mullen" <
notifications@github.com> написал:
