### ISSUE TITLE
hunspell

### ISSUE THREAD

**Issue by jeroen** [ropensci/tokenizers#19]
The new version of [hunspell](http://www.rdocumentation.org/packages/hunspell/versions/1.4.3/topics/hunspell) works on all platforms and has zero dependencies (it bundles the libhunspell source code). The package includes a speller (`hunspell_check`), stemmer (`hunspell_stem`) and tokenizer (`hunspell_parse`) which can parse formats `text`, `man`, `latex`, `html` or `xml`.

**Comment by lmullen** [comment]
Thanks, @jeroenooms! I'll look forward to looking into it.
