### ISSUE TITLE
Using long vectors

### ISSUE THREAD

**Issue by lmullen** [ropensci/tokenizers#21]
From [rOpenSci onboarding](https://github.com/ropensci/onboarding/issues/33#issuecomment-239488688):

> https://github.com/lmullen/tokenizers/blob/d240cddbb1d91146b3a30b90f6fc25abd6919edf/src/skip_ngrams.cpp#L9: If you want to support long vectors in R, you likely want to return and use R_xlen_t for indexing.

**Comment by dselivanov** [comment]
IMHO we are safe and should close this issue. Can't imagine the case when it can be useful to use `skip_grams > 10`
