### ISSUE TITLE
Ideas for other tokenizers

### ISSUE THREAD

**Issue by lmullen** [ropensci/tokenizers#27]
- extract noun phrases as in word2vec and the wordVectors package

**Comment by dselivanov** [comment]
This is done in `text2vec::Collocations` (with more heuristics). Actually this is not related to `word2vec` algorithm at all. 
Check this issue for inspiration https://github.com/dselivanov/text2vec/issues/99.

This also can be improved with information about POS tags. For example check [phrasemachine](https://github.com/slanglab/phrasemachine). I didn't try it yet, but it looks interesting.

**Comment by lmullen** [comment]
@dselivanov Ah, brilliant. I'll look forward to using that soon. Going to close this issue, then.
