### ISSUE TITLE
Add function to chunk texts into smaller segments

### ISSUE THREAD

**Issue by lmullen** [ropensci/tokenizers#30]
Suggested by @rccordell. Development in this branch. https://github.com/ropensci/tokenizers/blob/chunk-text/R/chunk-text.R

**Comment by lmullen** [comment]
This has been merged into master, but some work still needs to be done:

- [x] Check documentation
- [x] Check performance
- [ ] Add tests

**Comment by Ironholds** [comment]
LMK if you run into performance implications and I'm happy to try moving it compile-side

**Comment by lmullen** [comment]
@Ironholds Will do.
