### ISSUE TITLE
Add stopwords argument to `tokenize_skip_ngrams()`

### ISSUE THREAD

**Issue by lmullen** [ropensci/tokenizers#31]

**Comment by Ironholds** [comment]
I'll work on this next - can I suggest assigning #31 and #33 to me? Also happy to do #24 but I'm not sure if I have a sufficient background in this kind of text processing - if someone were to write out really inefficient R pseudocode for what you want, though, I could turn it into C++ no trouble.

**Comment by lmullen** [comment]
@Ironholds You're welcome to tackle #31 and #33. For some reason I can't assign you the issues in GitHub at the moment, probably because rOpenSci owns the repo not me. But they are all yours. 

I'm going to take a stab at #24 then let you clean up my C++. :-) It might take me a while to get to it, so if you finish the others and want something else to do, let me know and I'll mock something up.

**Comment by Ironholds** [comment]
Sounds good!
