### ISSUE TITLE
NA support?

### ISSUE THREAD

**Issue by Ironholds** [ropensci/tokenizers#33]
It should be possible to have the tokenisers and ngram generators:

1. Return NA when an NA is passed in;
2. Ignore NAs in input stopword lists;
3. Return NAs for empty output vectors.

Which of these are desirable, if any?

**Comment by lmullen** [comment]
Here is the current output that I get for those scenarios.

``` r
library(tokenizers)
test <- c("This is a text", NA, "So is this")
names(test) <- letters[1:3]
stops <- c("a", NA)
# Input with NA
tokenize_words(test)
#> $a
#> [1] "this" "is"   "a"    "text"
#> 
#> $b
#> [1] NA
#> 
#> $c
#> [1] "so"   "is"   "this"
# Input with NA
tokenize_ngrams(test, n = 2)
#> $a
#> [1] "this is" "is a"    "a text" 
#> 
#> $b
#> character(0)
#> 
#> $c
#> [1] "so is"   "is this"
# Input with NA, stopwords with NA
tokenize_words(test, stopwords = stops)
#> $a
#> [1] "this" "is"   "text"
#> 
#> $b
#> character(0)
#> 
#> $c
#> [1] "so"   "is"   "this"
# Input with NA, stopwords with NA
tokenize_ngrams(test, n = 2, stopwords = stops)
#> $a
#> [1] "this is" "is text"
#> 
#> $b
#> character(0)
#> 
#> $c
#> [1] "so is"   "is this"
```

So we don't fail on any of those inputs, but the output is inconsistent. I think we definitely want (1) and (3) from your list above, @Ironholds, to be true, so that NA's are returned. I don't currently see a problem with (2), unless I'm missing something.

**Comment by Ironholds** [comment]
Sounds good! Interesting - maybe Rcpp changed how it handles NAs? Or I'm missing a chunk of the code - basically historically NA_STRING got turned into the string 'na' if forcibly converted, meaning that if you had 'na' in the text you were checking against..yeah. Looks like it doesn't appear here, though.

Alright, I'll add this to the to-do (just as soon as the existing patch is merged. Do we know anyone with an old compiler?)

**Comment by Ironholds** [comment]
You want this for skip_ngrams too? that is, NA rather than an empty vector?

**Comment by lmullen** [comment]
@Ironholds Yes, that'd be great.
