### ISSUE TITLE
Lower level C++ api with external pointers

### ISSUE THREAD

**Issue by dselivanov** [ropensci/tokenizers#50]
The idea is to have option to receive `vector<vector<string>>` instead of list of character vectors (for example  it can look like `tokenize_words(..., as_xptr = TRUE)`). 

So packages can use lower level API. 
In particular I will be able to depreciate ngram-generation functionality in text2vec and rely solely on tokenizers (and to avoid [such confusion](https://github.com/ropensci/tokenizers/issues/47#issuecomment-294495889) ). Plus having this will reduce memory usage and allow easy thread parallelism. 

See details here - https://github.com/gagolews/stringi/issues/264

**Comment by lmullen** [comment]
@dselivanov Sounds like a good idea.

**Comment by Ironholds** [comment]
So would this be dependent on stringi?

**Comment by dselivanov** [comment]
I think so. 
I will make some experiments with simple whitespace tokenizer and post some results here.

**Comment by dselivanov** [comment]
I've done some experiments couple of month ago. Don't think this will bring a lot of speed-up (as I remember only 15-35%). So in my opinion it doesn't worth to focus on this issue. Also this will not help with memory fragmentation (see experiments [here](https://github.com/dselivanov/r-malloc), I personally switched to `jemalloc` and very happy).
