### ISSUE TITLE
tokenize_tweets and single word strings

### ISSUE THREAD

**Issue by juliasilge** [ropensci/tokenizers#70]
Hello! In juliasilge/tidytext#119, we have found what looks like an error for `tokenize_tweets()` in the case of an input character vector that is a single word/token.

``` r
library(tokenizers)

one_word_string <- "Word!"

tokenize_words(one_word_string)
#> [[1]]
#> [1] "word"
tokenize_sentences(one_word_string)
#> [[1]]
#> [1] "Word!"
tokenize_tweets(one_word_string)
#> Error in cut.default(seq_along(out), docindex, include.lowest = TRUE, : 'breaks' are not unique
```

Created on 2018-07-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Looks like it is happening [right here](https://github.com/ropensci/tokenizers/blob/39ce33d5b9e0b46513fd07734710aa28d4b32f83/R/tokenize_tweets.R#L84) when creating the output.

**Comment by lmullen** [comment]
This should be fixed on the master branch. I would appreciate it if you would test this in whatever circumstances are causing the error in tidytext, @juliasilge.

**Comment by juliasilge** [comment]
It is all fixed now and behaving correctly. Thanks so much, @lmullen! 🙌
