### ISSUE TITLE
Inconsistent behavior of tokenize_tweets() when filtering stopwords with punctuation

### ISSUE THREAD

**Issue by syumet** [ropensci/tokenizers#76]
Consider this example:
```
> library(tokenizers)
> tokenize_words("i'm happy!", stopwords = c("i'm"), strip_punct = T)
[[1]]
[1] "happy"

> tokenize_tweets("i'm happy!", stopwords = c("i'm"), strip_punct = T)
[[1]]
[1] "im"    "happy"
```

From my observation, `tokenize_tweets()` will remove punctuations before cleaning stopwords, that's probably the cause of the problem.

**Comment by kbenoit** [comment]
Fixed in a PR (still pending), thanks.

The **quanteda** package has a much upgraded default tokenizer in v2 by the way that handled social media tags even better and faster than `tokenize_tweets()`, without the problems you noticed.

**Comment by lmullen** [comment]
Thanks for the fix, @kbenoit.

@syumet: You should be able to install the development version with the fix via the `remotes` package.
