### ISSUE TITLE
Possible CRAN release 

### ISSUE THREAD

**Issue by EmilHvitfeldt** [ropensci/tokenizers#81]
Hello {tokenizers} maintainers! 👋 

Nothing but praise for this package!

I have been getting some users running into errors that occurred in the CRAN version of {tokenizers} but have been fixed in the github dev version of {tokenizers}. https://github.com/ropensci/tokenizers/commit/a4b824f5615ef26e5c3a07031133226c3fbb5df1 is one such fixed bug.

Would it be possible for you to do a CRAN release? as the last release was in April 2018. I would be happy to help do the work if this is a question of time/resources.

Best,
Emil

**Comment by lmullen** [comment]
@EmilHvitfeldt Thanks for the prompt. Yes, I can push up a CRAN release.

**Comment by lmullen** [comment]
Submitted 0.2.3 to CRAN.
