### ISSUE TITLE
tokenize_tweets replacement

### ISSUE THREAD

**Issue by alanault** [ropensci/tokenizers#84]
Hi there,

I noticed today that ```tokenize_tweets``` has been removed from the package without any deprecation. 

I saw the thread about CRAN compliance, which is obviously a real pain. Any suggestion on how to replace the same functionality, or whether the package will be updated to bring this function back again?

Many thanks
Alan

**Comment by lmullen** [comment]
Sorry for the sudden removal. You can find the code for the `tokenize_tweets()` function in this repository. I suggest you simply copy and paste it into your own source base.

**Comment by alanault** [comment]
Thanks for the quick response!
