### ISSUE TITLE
Add strip_url option to tokenize_words()

### ISSUE THREAD

**Issue by fschaffner** [ropensci/tokenizers#85]
Hi, thanks for maintaining this package!

I was wondering if a `strip_url = TRUE` option could be added to `tokenize_words()`? Or is there already a recommended way of removing URLs using `tokenize_words()`?

**Comment by lmullen** [comment]
I don't think this is something that I am willing to add at this point. This use is too highly specific for a general purpose package.

`tokenize_words()` will give you back a character vector. You can easily filter any character vector to remove URLs by writing, e.g., a regular expression that will detect a URL.
