### ISSUE TITLE
New Maintainer Welcome :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/tokenizers#86]
(or new maintainer _team_)

If you're interested, please comment in the issue or email `info@ropensci.org`.

For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html);
- [Package Maintainer Cheatsheet](https://devdevguide.netlify.app/maintenance_cheatsheet.html);
- the blog post [What does it mean to maintain a package?](https://ropensci.org/blog/2023/02/07/what-does-it-mean-to-maintain-a-package/).

@ropensci/admin @lmullen

**Comment by maelle** [comment]
@ThomasChln volunteered :tada: I'll let the issue open, @ThomasChln please close it once you've made changes in DESCRIPTION.

**Comment by ThomasChln** [comment]
Thanks Maëlle b80863d088d4b39695b602ca11e061ac34770ec7

**Comment by maelle** [comment]
Thank you!!
