### ISSUE TITLE
stopwords

### ISSUE THREAD

**Issue by dselivanov** [ropensci/tokenizers#9]
For the moment the simplest way to get stopwords - use `tm::stopwords`. But they are far from perfect. May be it worth to add modern stopwords lists to `tokenizers` package. As far as I know, [stopwords from lucene](https://github.com/apache/lucene-solr/tree/3f38aba02ce37c6422875d8824ee034d42d635b9/solr/contrib/morphlines-core/src/test-files/solr/collection1/conf/lang) are quite comprehensive.

**Comment by lmullen** [comment]
I agree that this is useful. I want to look more into this, since there are lots of different lists, then I'll add it to a later release.
